[tox]
minversion = 4.0
env_list = test_app,checks
skipsdist = true

[testenv]
passenv = *
allowlist_externals = bash

[testenv:test_app]
deps = -r test_requirements.txt
commands = pytest -q

[testenv:checks]
deps = -r typing_requirements.txt
commands =
    ruff check app src
    mypy app src
